### ISSUE TITLE
Favors command generation listing incorrect favors

### ISSUE THREAD

**Issue by HawkAtreides** [awgil/ffxiv_visland#87]
Possibly related to #86
This Week's Favors: Squid Ink / Macuahuitl / Sweet Popoto Pie
Generated Command: /favors favor1:Essential Draught favor2:Sauerkraut favor3:Peperoncino
Next Week's Favors: Earrings / Dried Flowers / Shark Oil
Generated Command: /favors favor1:Butter favor2:Powdered Paprika favor3:Silver Ear Cuffs

**Comment by Jaksuhn** [comment]
was this fixed along with #86 or is it something else

**Comment by HawkAtreides** [comment]
It seems to be fixed, though I'm having a separate issue - the favors command simply puts "Pie" in for "Islefish Pie", which gets an "invalid item" response from the OC Discord bot.

**Comment by Jaksuhn** [comment]
if you want to make a separate issue about it for documentation purposes, that's fine, but I don't really have an interest in continual support of the discord's favor system since they keep changing item names like that (inconsistently from the normal display) when we have a favor solver built in to the plugin already
